server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: movies
          uri: lb://movies
          predicates:
            - Path=/api/movies/**
          filters:
            - AutorizacionFilter
        - id: autenticacion
          uri: lb://autenticacion
          predicates:
            - Path=/api/autenticacion/**
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true